# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import customer_service_pb2 as customer__service__pb2

GRPC_GENERATED_VERSION = "1.66.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in customer_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class CustomerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListCustomers = channel.unary_unary(
            "/grpc_service.CustomerService/ListCustomers",
            request_serializer=customer__service__pb2.ListCustomersRequest.SerializeToString,
            response_deserializer=customer__service__pb2.CustomerListResponse.FromString,
            _registered_method=True,
        )
        self.GetCustomer = channel.unary_unary(
            "/grpc_service.CustomerService/GetCustomer",
            request_serializer=customer__service__pb2.GetCustomerRequest.SerializeToString,
            response_deserializer=customer__service__pb2.GetCustomerResponse.FromString,
            _registered_method=True,
        )


class CustomerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListCustomers(self, request, context):
        """Maps the ListCustomers method to a GET request on /v1/customers"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetCustomer(self, request, context):
        """Maps the GetCustomer method to a GET request on /v1/customers/{customer_id}"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CustomerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ListCustomers": grpc.unary_unary_rpc_method_handler(
            servicer.ListCustomers,
            request_deserializer=customer__service__pb2.ListCustomersRequest.FromString,
            response_serializer=customer__service__pb2.CustomerListResponse.SerializeToString,
        ),
        "GetCustomer": grpc.unary_unary_rpc_method_handler(
            servicer.GetCustomer,
            request_deserializer=customer__service__pb2.GetCustomerRequest.FromString,
            response_serializer=customer__service__pb2.GetCustomerResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "grpc_service.CustomerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "grpc_service.CustomerService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class CustomerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListCustomers(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/grpc_service.CustomerService/ListCustomers",
            customer__service__pb2.ListCustomersRequest.SerializeToString,
            customer__service__pb2.CustomerListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetCustomer(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/grpc_service.CustomerService/GetCustomer",
            customer__service__pb2.GetCustomerRequest.SerializeToString,
            customer__service__pb2.GetCustomerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
