# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import utility_request_pb2 as utility__request__pb2

GRPC_GENERATED_VERSION = "1.66.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in utility_request_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class UtilityServicesStub(object):
    """Service definition"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListUtilityServices = channel.unary_unary(
            "/grpc_service.utility.UtilityServices/ListUtilityServices",
            request_serializer=utility__request__pb2.ListUtilityRequest.SerializeToString,
            response_deserializer=utility__request__pb2.ListUtilityResponse.FromString,
            _registered_method=True,
        )
        self.FetchUtilityRequest = channel.unary_unary(
            "/grpc_service.utility.UtilityServices/FetchUtilityRequest",
            request_serializer=utility__request__pb2.UtilityServiceRequest.SerializeToString,
            response_deserializer=utility__request__pb2.UtilityServiceResponse.FromString,
            _registered_method=True,
        )


class UtilityServicesServicer(object):
    """Service definition"""

    def ListUtilityServices(self, request, context):
        """Maps the ListUtilityRequest method to a GET request on /v1/utility_request"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def FetchUtilityRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_UtilityServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ListUtilityServices": grpc.unary_unary_rpc_method_handler(
            servicer.ListUtilityServices,
            request_deserializer=utility__request__pb2.ListUtilityRequest.FromString,
            response_serializer=utility__request__pb2.ListUtilityResponse.SerializeToString,
        ),
        "FetchUtilityRequest": grpc.unary_unary_rpc_method_handler(
            servicer.FetchUtilityRequest,
            request_deserializer=utility__request__pb2.UtilityServiceRequest.FromString,
            response_serializer=utility__request__pb2.UtilityServiceResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "grpc_service.utility.UtilityServices", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "grpc_service.utility.UtilityServices", rpc_method_handlers
    )


class UtilityServices(object):
    """Service definition"""

    @staticmethod
    def ListUtilityServices(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/grpc_service.utility.UtilityServices/ListUtilityServices",
            utility__request__pb2.ListUtilityRequest.SerializeToString,
            utility__request__pb2.ListUtilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def FetchUtilityRequest(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/grpc_service.utility.UtilityServices/FetchUtilityRequest",
            utility__request__pb2.UtilityServiceRequest.SerializeToString,
            utility__request__pb2.UtilityServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
